### test fetch product info
GET http://localhost:8000/api/products/1

### test signin function
POST http://localhost:8000/api/users/signin
content-type: application/json

{
    "email":"admin@example.com",
    "password" : "123456"
}

### 
GET http://localhost:8000/api/seed/

### test signup function
POST http://localhost:8000/api/users/signup
content-type: application/json

{
    "name":"test5",
    "email":"test5@example.com",
    "password" : "123456"
}
